### ISSUE TITLE
Security STAT issues with pulsar-flink-connector-2.12-1.11-2.5.8.4

### ISSUE THREAD

**Issue by MSShravan** [streamnative/pulsar-flink#305]
Security scans have reported below STAT vulnerabilities that require attention.

CVE-2020-28052 
CVE-2021-28165

**Comment by jianyun8023** [comment]
@MSShravan  You can upgrade to the new version [pulsar-flink-connector_2.12](https://mvnrepository.com/artifact/io.streamnative.connectors/pulsar-flink-connector_2.12/1.11.1.0), This version will no longer rely on all shades in the connector package, and you can flexibly control the dependencies you need according to your needs.

In order to solve the CVE problem, you need to refer to the following configuration:
> `pulsar-client-all:2.7.1.4` comes from the weekly release of sn and needs to add a repository.

```xml
<dependencies>
<dependency>
    <groupId>io.streamnative.connectors</groupId>
    <artifactId>pulsar-flink-connector_2.12</artifactId>
    <version>1.11.1.0</version>
    <exclusions>
        <exclusion>
          <groupId>org.apache.pulsar</groupId>
          <artifactId>pulsar-client-all</artifactId>
        </exclusion>
      </exclusions>
</dependency>
<dependency>
      <groupId>org.apache.pulsar</groupId>
      <artifactId>pulsar-client-all</artifactId>
      <version>2.7.1.4</version>
</dependency>
</dependencies>
  <repositories>
    <repository>
      <id>central</id>
      <layout>default</layout>
      <url>https://repo1.maven.org/maven2</url>
    </repository>
    <repository>
      <id>bintray-streamnative-maven</id>
      <name>bintray</name>
      <url>https://dl.bintray.com/streamnative/maven</url>
    </repository>
  </repositories>
```
